= DevPod Provider Podman
:hack: ./hack/provider

A provider to launch link:https://devpod.sh[DevPod] workspaces on Podman.


== Getting Started

[source,shell]
----
devpod provider add babeloff/devpod-provider-podman
----

== Operation

https://devpod.sh/docs/developing-providers/quickstart#how-devpod-interacts-with-a-provider

As this is a Non-Machine provider
link:https://devpod.sh/docs/developing-providers/quickstart#non-machine-provider[only the following execs are used]:

.command
[source,yaml]
----
include::{hack}/provider.yml[tag=exec-command]
----
The `command` is required for a provider to work,
it defines how to run a command in the environment.
DevPod uses `command` to inject itself into the environment
routing all communication through standard output and input.
An example for a local development provider should use `devpod helper`.


.init
[source,yaml]
----
include::{hack}/provider.yml[tag=exec-init]
----
Optional command to check if options are defined correctly
and the provider is ready to create environments.
For example for this provider,
`init` checks that Podman is installed and reachable locally.

== Releasing

To release this project.
Go to https://github.com/babeloff/devpod-provider-podman/releases
and select a tag representing the release.
The tag should use CalVer (`vYYYY-MM-PP`).
In order to trigger the release job the tag must begin with `v`.
If a release is a patch,
it should not update the `YYYY-MM` portion even if patched and released on a different date.
On the major release the PP should be `00`.

== Reference

. link:https://devpod.sh/docs/developing-providers/quickstart[Quick Start]
. link:https://github.com/ThomasVitale/devpod-provider-podman[Forked Project]
